micronaut:
  application:
    name: keyManagerGrpc
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/keymanager
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    dialect:
#gera a tabela automaticamente banco de dados
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true